var g_CONSUME_EVENT = {};
g_CONSUME_EVENT.types = {REPU:{CONSUME_CONVERT:40,POINT_CONVERT:4,GROUPS:{},RATES:{}},COIN:{CONSUME_CONVERT:25,POINT_CONVERT:20,GROUPS:{},RATES:{}},GOLD:{CONSUME_CONVERT:25000,POINT_CONVERT:8,GROUPS:{},RATES:{}}};
