var g_JACKS_GARDEN = {};
g_JACKS_GARDEN.MACHINES = {1:{DURABILITY_MIN:1,DURABILITY_MAX:2},31:{DURABILITY_MIN:3,DURABILITY_MAX:4},51:{DURABILITY_MIN:5,DURABILITY_MAX:6},81:{DURABILITY_MIN:7,DURABILITY_MAX:8},151:{DURABILITY_MIN:9,DURABILITY_MAX:10}};
